apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-cluster
  region: us-east-1

iam:
  withOIDC: true
  serviceRoleARN: "arn:aws:iam::533267189120:role/LabRole"

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 2
    iam:
      instanceRoleARN: "arn:aws:iam::533267189120:role/LabRole"
